# .gitlab-ci.yml

# 定义构建和部署阶段
stages:
  - build
  - deploy

# 编译/打包项目（例如，使用 npm 或 yarn）
build:
  stage: build
  script:
    - pnpm install    # 安装依赖（如果你使用 npm）
    - pnpm build  # 编译/打包你的网站
  artifacts:
    paths:
      - dist/  # 指定需要部署到 Pages 的目录
    expire_in: 1 hour  # 保留 artifacts 的时间，可选

# 部署到 GitLab Pages
pages:
  stage: deploy
  artifacts:
    paths:
      - dist/  # 指定 GitLab Pages 应该从哪个目录读取文件
    expire_in: 1 week  # 保留 Pages 的时间，可选
  only:
    - master  # 只在 main 分支上部署 Pages（你可以根据需要更改）
